# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_auto_20180613_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about_us',
            new_name='About',
        ),
    ]
