# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_auto_20180614_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
