# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0007_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='pos',
            new_name='position',
        ),
    ]
