# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-07 22:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 7, 7, 22, 49, 22, 256000, tzinfo=utc))),
            ],
        ),
    ]
