# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-28 23:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 28, 23, 15, 25, 106000, tzinfo=utc)),
        ),
    ]
