# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-02 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180628_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 2, 14, 45, 13, 352000, tzinfo=utc)),
        ),
    ]
