# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-07 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180707_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 23, 9, 41, 546000, tzinfo=utc)),
        ),
    ]
