# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-08 01:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180707_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 8, 1, 39, 49, 135000, tzinfo=utc)),
        ),
    ]
